fix-cron-simplify-rabbitmq-remove-consul
ergonode/docker pull request #57
Opened 2020-10-05 18:13 UTC by Daniel-Marynicz

2020-10-05 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ergonode/docker?pullRequest=57) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ergonode/docker?pullRequest=57) before we can accept your contribution.<br/><hr/>**Daniel Marynicz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ergonode/docker?pullRequest=57) it.</sub>

2020-10-05 18:16 UTC, BastekBielawski submitted a review, later dismissed

2020-10-05 20:14 UTC, wfajczyk commented
What about the configuration `docker-compose.production.yml` ? When we delete rabbit from dockerfile then the production version will stop working

2020-10-06 07:56 UTC, wfajczyk requested changes
`docker-compose.production.yml`

2020-10-06 15:48 UTC, BastekBielawski approved these changes

2020-10-08 10:52 UTC, wfajczyk approved these changes

2022-11-30 10:47 UTC, closed without merging